/** CSS styles for the Model Pro settings page. */

export const CSS = [
  '.mpro-root{--mpro-gap:16px;--mpro-radius:10px;--mpro-radius-sm:6px;max-width:760px;margin:0 auto;padding:0 0 40px;color:var(--dsw-alias-label-primary);font-size:13px;line-height:1.5}',
  '.mpro-head{display:flex;align-items:baseline;justify-content:space-between;margin-bottom:4px}',
  '.mpro-head h2{font-size:18px;font-weight:600;margin:0;letter-spacing:-0.01em}',
  '.mpro-headActions{display:flex;gap:6px;align-items:center}',
  '.mpro-intro{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.6;margin:0 0 20px}',
  '.mpro-banner{padding:8px 12px;border-radius:var(--mpro-radius-sm);font-size:12px;margin-bottom:12px}',
  '.mpro-bannerOk{background:var(--dsw-alias-state-success-fill);color:var(--dsw-alias-state-success-label)}',
  '.mpro-bannerErr{background:var(--dsw-alias-state-error-fill);color:var(--dsw-alias-state-error-label)}',
  '.mpro-bannerWarn{background:var(--dsw-alias-state-warn-fill);color:var(--dsw-alias-state-warn-label)}',
  '.mpro-btn{height:28px;padding:0 12px;border-radius:var(--mpro-radius-sm);border:1px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-primary);font-size:12px;font-family:inherit;cursor:pointer;white-space:nowrap;transition:background .12s,border-color .12s;display:inline-flex;align-items:center;gap:4px}',
  '.mpro-btn:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}',
  '.mpro-btn:disabled{opacity:.4;cursor:default}',
  '.mpro-btnPrimary{background:var(--dsw-alias-brand-primary);color:#fff;border-color:transparent}',
  '.mpro-btnPrimary:hover:not(:disabled){background:var(--dsw-alias-brand-primary-hover,var(--dsw-alias-brand-primary))}',
  '.mpro-btnDanger{color:var(--dsw-alias-state-error-primary)}',
  '.mpro-btnDanger:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover-danger)}',
  '.mpro-btnSm{height:24px;padding:0 8px;font-size:11px}',
  '.mpro-card{background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l1);border-radius:var(--mpro-radius);padding:0;overflow:hidden}',
  '.mpro-cardHead{display:flex;align-items:center;justify-content:space-between;padding:12px 16px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.mpro-cardTitle{font-size:13px;font-weight:600;margin:0}',
  '.mpro-cardBody{padding:12px 16px;display:flex;flex-direction:column;gap:12px}',
  '.mpro-grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}',
  '.mpro-grid2 .mpro-fieldFull{grid-column:1/-1}',
  '.mpro-field{display:flex;flex-direction:column;gap:4px}',
  '.mpro-fieldLabel{font-size:11px;font-weight:500;color:var(--dsw-alias-label-secondary);text-transform:uppercase;letter-spacing:0.04em}',
  '.mpro-input{box-sizing:border-box;width:100%;height:30px;padding:0 10px;border-radius:var(--mpro-radius-sm);border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font-family:inherit;font-size:12px;transition:border-color .12s}',
  '.mpro-input:focus{outline:none;border-color:var(--dsw-alias-brand-primary)}',
  '.mpro-input::placeholder{color:var(--dsw-alias-label-quaternary)}',
  '.mpro-select{appearance:auto;cursor:pointer}',
  '.mpro-hint{font-size:11px;color:var(--dsw-alias-label-tertiary);line-height:1.5;margin:0}',
  '.mpro-pcList{display:flex;flex-direction:column;gap:8px}',
  '.mpro-pc{display:flex;align-items:center;gap:12px;padding:12px 14px;border:1px solid var(--dsw-alias-border-l1);border-radius:var(--mpro-radius);background:var(--dsw-alias-bg-layer-2);transition:border-color .12s}',
  '.mpro-pc:hover{border-color:var(--dsw-alias-border-l2)}',
  '.mpro-pcDisabled{opacity:.55}',
  '.mpro-pcDot{flex:none;width:8px;height:8px;border-radius:50%;background:var(--dsw-alias-state-success-primary)}',
  '.mpro-pcDotOff{background:var(--dsw-alias-state-error-primary)}',
  '.mpro-pcDotCat{background:var(--dsw-alias-brand-primary)}',
  '.mpro-pcInfo{flex:1;min-width:0;display:flex;flex-direction:column;gap:2px}',
  '.mpro-pcName{font-size:13px;font-weight:600;display:flex;align-items:center;gap:6px}',
  '.mpro-pcMeta{font-size:11px;color:var(--dsw-alias-label-tertiary);display:flex;gap:10px;flex-wrap:wrap}',
  '.mpro-pcMeta span{white-space:nowrap}',
  '.mpro-pcActions{display:flex;gap:4px;align-items:center;flex:none}',
  '.mpro-tag{display:inline-block;padding:0 5px;height:18px;line-height:18px;border-radius:3px;font-size:10px;font-weight:500;letter-spacing:.02em}',
  '.mpro-tagCat{background:var(--dsw-alias-brand-primary-alpha-15,rgba(99,102,241,.12));color:var(--dsw-alias-brand-primary)}',
  '.mpro-tagExp{background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-secondary)}',
  '.mpro-tagOff{background:var(--dsw-alias-state-error-fill);color:var(--dsw-alias-state-error-label)}',
  '.mpro-tabs{display:flex;gap:0;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.mpro-tab{padding:8px 16px;font-size:12px;font-weight:500;color:var(--dsw-alias-label-secondary);cursor:pointer;border:none;background:none;border-bottom:2px solid transparent;transition:color .12s,border-color .12s;font-family:inherit}',
  '.mpro-tab:hover{color:var(--dsw-alias-label-primary)}',
  '.mpro-tabActive{color:var(--dsw-alias-brand-primary);border-bottom-color:var(--dsw-alias-brand-primary)}',
  '.mpro-editorHead{display:flex;align-items:center;gap:10px;padding:12px 16px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.mpro-editorRoute{font-size:15px;font-weight:600;margin:0;flex:1}',
  '.mpro-hdrRow{display:grid;grid-template-columns:160px 1fr 28px;gap:8px;align-items:center}',
  '.mpro-modelBar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:8px}',
  '.mpro-modelBar .mpro-chip{margin-left:auto}',
  '.mpro-chip{display:inline-flex;align-items:center;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:500;background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-secondary)}',
  '.mpro-tblWrap{overflow-x:auto;border:1px solid var(--dsw-alias-border-l1);border-radius:var(--mpro-radius-sm)}',
  '.mpro-tbl{width:100%;border-collapse:collapse;font-size:11px}',
  '.mpro-tbl th{text-align:left;padding:6px 10px;font-weight:500;color:var(--dsw-alias-label-secondary);border-bottom:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-2);white-space:nowrap}',
  '.mpro-tbl td{padding:5px 10px;border-bottom:1px solid var(--dsw-alias-border-l1)}',
  '.mpro-tbl tr:last-child td{border-bottom:none}',
  '.mpro-tbl tbody tr:hover{background:var(--dsw-alias-interactive-bg-hover)}',
  '.mpro-tblCk{text-align:center;width:28px}',
  '.mpro-emptyState{padding:24px 16px;text-align:center;color:var(--dsw-alias-label-tertiary);font-size:12px}',
  '.mpro-inlineStatus{font-size:11px;padding:2px 0}',
  '.mpro-inlineStatusOk{color:var(--dsw-alias-state-success-primary)}',
  '.mpro-inlineStatusErr{color:var(--dsw-alias-state-error-primary)}',
  '@media(max-width:600px){.mpro-grid2{grid-template-columns:1fr}.mpro-hdrRow{grid-template-columns:120px 1fr 24px}}',
].join('\n')
